// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS9FUvVJYiHeQjubyP4wmEedqLy5tw3ek',
    appId: '1:887235051913:web:3b9d5d80cdbfb331496158',
    messagingSenderId: '887235051913',
    projectId: 'bingoadmin-c4015',
    authDomain: 'bingoadmin-c4015.firebaseapp.com',
    storageBucket: 'bingoadmin-c4015.appspot.com',
    measurementId: 'G-V0SFYLYSBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9SHgfhpBayh56jZGoviqjLgB_v75kU4',
    appId: '1:887235051913:android:e533615b265970c5496158',
    messagingSenderId: '887235051913',
    projectId: 'bingoadmin-c4015',
    storageBucket: 'bingoadmin-c4015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEEh49sB5v28_IyAVfz_iU0aNs0qng_3M',
    appId: '1:887235051913:ios:29bd3f470c83b12b496158',
    messagingSenderId: '887235051913',
    projectId: 'bingoadmin-c4015',
    storageBucket: 'bingoadmin-c4015.appspot.com',
    iosBundleId: 'br.com.fabioalvaro.admin.bingoadmin',
  );
}
